Repository jenkinsci/google-storage-plugin, pull requests merged in 2023-12, with the labels that each got.

#268 Use Guava from Jenkins core
  pom.xml
Labels: maintenance

#271 Remove unnecessary JARs from HPI
  pom.xml
Labels: bug, maintenance

#277 Bump version of google-oauth-plugin and fix the tests
  pom.xml
  src/test/java/com/google/jenkins/plugins/storage/ClassicUploadStepTest.java
  src/test/java/com/google/jenkins/plugins/storage/DownloadStepTest.java
  src/test/java/com/google/jenkins/plugins/storage/ExpiringBucketLifecycleManagerStepTest.java
  src/test/java/com/google/jenkins/plugins/storage/StdoutUploadStepTest.java
Labels: chore

#280 Require Jenkins 2.401.3 or newer
  pom.xml
Labels: developer
